/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntoa;

import javax.swing.JOptionPane;

/**
 *
 * @author jorgeeduardo
 */
public class hipotenusa extends javax.swing.JFrame {

    /**
     * Creates new form hipotenusa
     */
    public hipotenusa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcatetoop = new javax.swing.JTextField();
        txtcatetoad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 340));
        setMinimumSize(new java.awt.Dimension(400, 340));
        setPreferredSize(new java.awt.Dimension(400, 340));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("   CATETO OPUESTO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 60, 100, 40);

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("CATETO ADYACENTE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 130, 110, 30);

        txtcatetoop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcatetoopActionPerformed(evt);
            }
        });
        getContentPane().add(txtcatetoop);
        txtcatetoop.setBounds(150, 90, 70, 30);
        getContentPane().add(txtcatetoad);
        txtcatetoad.setBounds(140, 160, 80, 30);

        jButton1.setBackground(new java.awt.Color(51, 255, 255));
        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 220, 110, 40);

        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 220, 90, 40);
        getContentPane().add(txtResultado);
        txtResultado.setBounds(140, 220, 130, 40);

        jLabel3.setText("                                            HALLAR HIPOTENUSA");
        jLabel3.setMaximumSize(new java.awt.Dimension(300, 20));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 0, 330, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/400_F_42192797_U6zfQvoRltUENszfjFqwNT5EAziGu5rF.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcatetoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcatetoopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcatetoopActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
    
 
        double Hipotenusa;
        double dato1 = Double.parseDouble(txtcatetoop.getText());
        double dato2 = Double.parseDouble(txtcatetoad.getText());
        jh Calcular = new jh();
        Hipotenusa = Calcular.hallar_hipotenusa(dato1, dato2);
        txtResultado.setText(String.valueOf(Hipotenusa));
}
catch(NumberFormatException e){
    JOptionPane.showMessageDialog(null, "Ingrese un número válido.","///ERROR///", JOptionPane.WARNING_MESSAGE);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      txtcatetoop.setText(" ");
      txtcatetoad.setText(" ");
      txtResultado.setText(" ");
      
      
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hipotenusa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hipotenusa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hipotenusa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hipotenusa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hipotenusa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtcatetoad;
    private javax.swing.JTextField txtcatetoop;
    // End of variables declaration//GEN-END:variables
}
