
package capitulo4;

import javax.swing.JOptionPane;
import java.io.IOException;

public class Ejer11 extends javax.swing.JFrame {

    public Ejer11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtn1 = new javax.swing.JTextField();
        txtn2 = new javax.swing.JTextField();
        txtn3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtresultado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 340));
        setMinimumSize(new java.awt.Dimension(400, 340));
        setPreferredSize(new java.awt.Dimension(400, 340));
        getContentPane().setLayout(null);
        getContentPane().add(txtn1);
        txtn1.setBounds(120, 40, 90, 30);
        getContentPane().add(txtn2);
        txtn2.setBounds(120, 80, 90, 30);
        getContentPane().add(txtn3);
        txtn3.setBounds(120, 120, 90, 30);

        jLabel1.setText("Primer Numero");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 34, 90, 30);

        jLabel2.setText("segundo valor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 90, 30);

        jLabel3.setText("tercer valor");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 130, 80, 20);

        jButton1.setText("comparar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 210, 120, 60);

        jButton2.setText("limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 260, 80, 40);
        getContentPane().add(txtresultado);
        txtresultado.setBounds(70, 160, 220, 40);

        jLabel4.setFont(new java.awt.Font("Wide Latin", 3, 11)); // NOI18N
        jLabel4.setText("NUMERO MAYOR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 0, 220, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            int N1 , N2 ,N3;
            String texto;
            N1 = Integer.parseInt(txtn1.getText());
            N2 =  Integer.parseInt(txtn2.getText());
            N3 =  Integer.parseInt(txtn3.getText());
            Jorge val = new Jorge();
            texto = val.Comparar_valores(N1, N2, N3);
            txtresultado.setText(texto);
        }
        catch(Exception errodato)
        {
            JOptionPane.showMessageDialog(null, "datos erroneos", "ERROR!!!", WIDTH);
            txtn1.setText("");
            txtn2.setText("");
            txtn3.setText("");
            txtresultado.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            txtn1.setText("");
            txtn2.setText("");
            txtn3.setText("");
            txtresultado.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejer11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejer11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejer11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejer11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejer11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtn1;
    private javax.swing.JTextField txtn2;
    private javax.swing.JTextField txtn3;
    private javax.swing.JTextField txtresultado;
    // End of variables declaration//GEN-END:variables
}
