/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capitulo4;

import javax.swing.JOptionPane;

/**
 *
 * @author jorgeeduardo
 */
public class ejer10 extends javax.swing.JFrame {

    /**
     * Creates new form ejer10
     */
    public ejer10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        txtNi = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtest = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 340));
        setMinimumSize(new java.awt.Dimension(400, 340));
        setPreferredSize(new java.awt.Dimension(400, 340));
        getContentPane().setLayout(null);

        jLabel1.setText("         PAGO DE MATRICULA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(104, 11, 176, 31);

        jLabel2.setText("Digite su nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 140, 20);

        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        getContentPane().add(txtnom);
        txtnom.setBounds(160, 40, 120, 30);

        jLabel3.setText("Digite numero de inscripcion");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 150, 14);
        getContentPane().add(txtni);
        txtni.setBounds(160, 70, 120, 30);

        jLabel4.setText("Digite su patrimonio");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 110, 140, 14);
        getContentPane().add(txtpat);
        txtpat.setBounds(160, 100, 120, 30);

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 220, 100, 30);
        getContentPane().add(txtnombre);
        txtnombre.setBounds(95, 201, 171, 28);
        getContentPane().add(txtNi);
        txtNi.setBounds(95, 235, 171, 32);
        getContentPane().add(txtTotal);
        txtTotal.setBounds(95, 273, 171, 31);

        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 250, 100, 30);

        jLabel5.setText("Digite su estrato");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 140, 140, 14);
        getContentPane().add(txtest);
        txtest.setBounds(160, 130, 120, 30);

        jLabel6.setText("Nº Inscripcion:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(4, 244, 90, 20);

        jLabel7.setText("Nombre:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 210, 60, 14);

        jLabel8.setText("Total a pagar:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 280, 90, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String Nombre;
            Nombre = (txtnom.getText());

            double ni = Double.parseDouble(txtni.getText());
            double pat = Double.parseDouble(txtpat.getText());
            int PAGMAT = 50000;
            double est = Double.parseDouble(txtest.getText());
            if (pat > 2000000 && est > 3) {
                PAGMAT += 0.03 * pat;
            }
            txtnombre.setText(String.valueOf(Nombre));
            txtNi.setText(String.valueOf(ni));
            txtTotal.setText(String.valueOf(PAGMAT));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un número válido.", "///ERROR///", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           txtpat.setText(" ");
        txtest.setText(" ");
           txtnom.setText(" ");
           txtni.setText(" ");
        txtTotal.setText(" ");
        txtNi.setText(" ");
        txtnombre.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejer10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejer10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejer10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejer10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejer10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField txtNi;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtest;
    private javax.swing.JTextField txtni;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpat;
    // End of variables declaration//GEN-END:variables
}
