/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capitulo4;

import javax.swing.JOptionPane;
import java.io.IOException;

/**
 *
 * @author Linda Charris
 */
public class Ejer13 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ejer13() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtvalcomp = new javax.swing.JTextField();
        txtcolor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtresultado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 340));
        setMinimumSize(new java.awt.Dimension(400, 340));
        setPreferredSize(new java.awt.Dimension(400, 340));
        getContentPane().setLayout(null);

        jLabel1.setText("Valor de la compra:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 140, 20);

        jLabel2.setText("Color de la pelota:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 94, 140, 10);
        getContentPane().add(txtvalcomp);
        txtvalcomp.setBounds(150, 40, 120, 30);
        getContentPane().add(txtcolor);
        txtcolor.setBounds(150, 80, 120, 30);

        jLabel3.setText("Total a pagar:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 130, 100, 14);
        getContentPane().add(txtresultado);
        txtresultado.setBounds(150, 120, 120, 30);

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(55, 167, 110, 50);

        jButton2.setText("limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(197, 167, 100, 40);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 11)); // NOI18N
        jLabel4.setText("VALOR A PAGAR POR LA COMPRA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 0, 270, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         double  VALCOMP, PDES = 0, total , VALPAG;
         String COLOR;
        try
        {
           
         VALCOMP = Double.parseDouble(txtvalcomp.getText());
         COLOR = txtcolor.getText();
         switch (COLOR) {
            case "verde":
                PDES = VALCOMP *10 / 100 ;
                break;
            case "amarillo":
                PDES = VALCOMP *25 / 100 ;
                break;
            case "azul":
                PDES = VALCOMP *50 / 100 ;
                break;
            case "rojo":
                PDES = VALCOMP ;
                break;
        }
       
        VALPAG =   VALCOMP - PDES;
         txtresultado.setText(String.valueOf(VALPAG));
        }
        catch(Exception errordato)
        {
            JOptionPane.showMessageDialog(this, "Dato incorrecto\n ingrese nuevos datos", "ERROR!!!", WIDTH);
            txtvalcomp.setText("");
             txtcolor.setText("");
              txtresultado.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          txtvalcomp.setText("");
             txtcolor.setText("");
              txtresultado.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejer13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejer13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejer13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejer13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejer13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtresultado;
    private javax.swing.JTextField txtvalcomp;
    // End of variables declaration//GEN-END:variables
}
