/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capitulo4;

import javax.swing.JOptionPane;

/**
 *
 * @author jorgeeduardo
 */
public class mayor extends javax.swing.JFrame {

    /**
     * Creates new form mayor
     */
    public mayor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdato1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdato2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtresultado = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 340));
        setMinimumSize(new java.awt.Dimension(400, 340));
        setPreferredSize(new java.awt.Dimension(400, 340));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("NUMERO MAYOR O IGUAL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 0, 280, 70);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("Ingrese Numero A");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 140, 23);

        txtdato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdato1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtdato1);
        txtdato1.setBounds(180, 70, 80, 30);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setText("Ingrese Numero B");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 140, 15);

        txtdato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdato2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtdato2);
        txtdato2.setBounds(180, 120, 80, 34);

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 240, 110, 44);

        txtresultado.setBackground(new java.awt.Color(204, 0, 51));
        getContentPane().add(txtresultado);
        txtresultado.setBounds(100, 190, 213, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 260, 85, 33);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo/Casa-Orgánica-exterior1-400x400.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 410, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdato1ActionPerformed

    private void txtdato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdato2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdato2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String mayoroigual;
            double num1 = Double.parseDouble(txtdato1.getText());
            double num2 = Double.parseDouble(txtdato2.getText());
            if (num1 == num2) {
                mayoroigual = ("numero a es igual a numero b");
            } else if (num1 > num2) {
                mayoroigual = ("numero a es mayor que b");
            } else {
                mayoroigual = ("numero b es mayor que numero a");
            }

            txtresultado.setText(String.valueOf(mayoroigual));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un número válido.", "///ERROR///", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtdato1.setText(" ");
        txtdato2.setText(" ");
        txtresultado.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mayor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtdato1;
    private javax.swing.JTextField txtdato2;
    private javax.swing.JTextField txtresultado;
    // End of variables declaration//GEN-END:variables
}
